name: DemarkExample
options:
  bundleIdPrefix: com.steipete.demark
  deploymentTarget:
    macOS: "14.0"
    iOS: "17.0"
  
settings:
  base:
    SWIFT_VERSION: "6.0"
    ENABLE_STRICT_SWIFT_CONCURRENCY: YES
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    
targets:
  DemarkExample:
    type: application
    platform: [macOS, iOS]
    sources:
      - path: Sources
    dependencies:
      - package: Demark
        product: Demark
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.steipete.demark.example
        SWIFT_STRICT_CONCURRENCY: complete
        SWIFT_UPCOMING_FEATURE_CONCISE_MAGIC_FILE: YES
        SWIFT_UPCOMING_FEATURE_FORWARD_TRAILING_CLOSURES: YES
        SWIFT_UPCOMING_FEATURE_GLOBAL_CONCURRENCY: YES
        SWIFT_UPCOMING_FEATURE_IMPLICIT_OPEN_EXISTENTIALS: YES
        SWIFT_UPCOMING_FEATURE_STRICT_CONCURRENCY: YES
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""

packages:
  Demark:
    path: ../

schemes:
  DemarkExample:
    build:
      targets:
        DemarkExample: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release