name: DemarkExample
options:
  bundleIdPrefix: com.steipete.demark
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "14.0"
    iOS: "17.0"
  
settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    ENABLE_STRICT_SWIFT_CONCURRENCY: YES
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    
targets:
  DemarkExample-iOS:
    type: application
    platform: iOS
    sources:
      - path: Sources
        excludes:
          - "**/macOS/**"
    dependencies:
      - package: Demark
        product: Demark
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.steipete.demark.example
        PRODUCT_NAME: "Demark Example"
        INFOPLIST_FILE: "Platforms/iOS/Info.plist"
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        ENABLE_PREVIEWS: YES
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        PROVISIONING_PROFILE_SPECIFIER: ""
        
  DemarkExample-macOS:
    type: application
    platform: macOS
    sources:
      - path: Sources
        excludes:
          - "**/iOS/**"
    dependencies:
      - package: Demark
        product: Demark
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.steipete.demark.example.mac
        PRODUCT_NAME: "Demark Example"
        INFOPLIST_FILE: "Platforms/macOS/Info.plist"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        ENABLE_HARDENED_RUNTIME: YES
        ENABLE_PREVIEWS: YES
        COMBINE_HIDPI_IMAGES: YES

packages:
  Demark:
    path: ../

schemes:
  DemarkExample-iOS:
    build:
      targets:
        DemarkExample-iOS: all
    run:
      config: Debug
      device: iPhone 15 Pro
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
      
  DemarkExample-macOS:
    build:
      targets:
        DemarkExample-macOS: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release